name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin' # Temurin is the new name for Adopt OpenJDK

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Ubuntu server
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP: 134.209.216.201
          APP_DIR: /opt/sidekick-api
          REMOTE_USER: root
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/sidekick-api.jar "${REMOTE_USER}@${SERVER_IP}:${APP_DIR}/"
          ssh -i private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${REMOTE_USER}@${SERVER_IP}" "sudo systemctl restart sidekick-api.service"